/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package ray.dedup

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

// @RunWith(classOf[JUnitRunner])
// class LibrarySuite extends FunSuite {
//   // test("someLibraryMethod is always true") {
//   //   // assert(1 == 1)
//   // }
// }
