/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dummy.process;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class App {
    private static final Logger logger = LogManager.getLogger(App.class);

    private ScheduledExecutorService memoryReaderScheduler = null;

    public App() {
        memoryReaderScheduler = Executors.newSingleThreadScheduledExecutor();
        memoryReaderScheduler.schedule(new MemoryReader(), 5, TimeUnit.SECONDS);
    }


    public void shutdown() {
        if (this.memoryReaderScheduler != null) {
            this.memoryReaderScheduler.shutdown();
        }
    }

    public static void main(String[] args) {
        logger.debug("Spawning memory reader scheduler");

        App app = new App();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            logger.debug("Shutting down");
            app.shutdown();
        }));

        while(true) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
